### ISSUE TITLE
is this MeanShift

### ISSUE THREAD

**Issue by Zhengjun-Du** [SamMaoYS/MeanShift#3]
Hi, I run your code, the results is very nice, thanks for your great work!
And I also read your code, but I really don't know where is the 'MeanShift' process, you perform BFS-like method for initial merge very similar pixels, and then merge those regions with less than 100 pixels.  

Another question, why you choose LUV space?  it indeed looks better than RGB space.

**Comment by SamMaoYS** [comment]
Hi @Zhengjun-Du, thank you for your interest in this mean-shift implementation. I am not an expert in mean-shift, and this codebase is written when I was trying to learn the mean-shift for image segmentation as a student.

I think the mean-shift is based on the probability density of the pixels in the image, the "mean" (center) of the similar pixels has high _probability density_, and other neighboring pixels will "shift" to the center. I think this is the 'MeanShift' process. The BFS-like method is used to search the high _probability density_ area, so the pixel knows where to shift.

For LUV space is mentioned in the original paper, and is actually broadly used in computer vision and graphics. LUV can have a better representation of the differences in color, for example, the same object with different brightness can have a large difference in RGB space, but can be similar in LUV space, as brightness only affects the L channel.

These are just my personal opinion, I highly recommend you read the original paper and the papers listed in the reference section in the readme.

**Comment by Zhengjun-Du** [comment]
Thanks for your quick response, best wishes!
